[package]
name = "supermarket"
version = "0.1.0"
authors = ["Lachezar Lechev <lachezar.lechev@adex.network>"]
edition = "2018"

[dependencies]
# Server
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
hyper = { version = "0.13", features = ["stream"] }
http = "0.2.0"

[dev-dependencies]
reqwest = "0.10"