# The list of Validators' Urls for fetching the Campaigns from
validators = ["http://localhost:8005/", "http://localhost:8006/"]

# in seconds - 4 minutes
recency = 240
fetch_campaigns_every = 60
update_campaigns_every = 20

[limits]
# if left out or commented out it won't be applied.
# 100 DAI/TST
limited_identity_earnings_limit = '100000000000000000000'

# The maximum number of campaigns a publisher can earn from
# This will limit the returned Campa\igns to the set number
max_channels_earning_from = 25

[timeouts]
cache_update_campaign_statuses = 10
cache_fetch_campaigns_from_market = 20
validator_request = 10
