# if left out or commented out it won't be applied.r
# 100 DAI/TST
limited_identity_earnings_limit = '100000000000000000000'

# 4 minutes
recency = 240
fetch_campaigns_every = 240
update_campaigns_every = 50

[timeouts]
cache_update_campaign_statuses = 40
cache_fetch_campaigns_from_market = 20
validator_request = 20
