# The list of Validators' Urls for fetching the Campaigns from
validators = ["https://jerry.adex.network/", "https://tom.adex.network/"]

# in seconds - 4 minutes
recency = 240
fetch_campaigns_every = 240
update_campaigns_every = 50

[limits]
# if left out or commented out it won't be applied.
# 100 DAI/TST
limited_identity_earnings_limit = '100000000000000000000'

# The maximum number of campaigns a publisher can earn from
# This will limit the returned Campaigns to the set number
max_channels_earning_from = 25

# 0.01 DAI per 1000 impressions
global_min_impression_price = '10000000000000';

[timeouts]
cache_update_campaign_statuses = 40
cache_fetch_campaigns_from_market = 20
validator_request = 20
